# Generated by Django 5.0.6 on 2026-09-15 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ad Soyad / Firma Adı')),
                ('tc_or_tax_no', models.CharField(blank=True, max_length=20, verbose_name='TC Kimlik No / Vergi No')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('driver_license_no', models.CharField(blank=True, max_length=30, verbose_name='Ehliyet No')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('pricing_type', models.CharField(choices=[('GUNLUK', 'Günlük'), ('AYLIK', 'Aylık'), ('YILLIK', 'Yıllık')], default='GUNLUK', max_length=10, verbose_name='Fiyatlandırma Tipi')),
                ('daily_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kiralama Anındaki Günlük Fiyat')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Toplam Tutar')),
                ('status', models.CharField(choices=[('REZERVE', 'Rezerve'), ('DEVAM_EDIYOR', 'Devam Ediyor'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL', 'İptal Edildi')], default='REZERVE', max_length=20, verbose_name='Durum')),
                ('payment_status', models.CharField(choices=[('BEKLIYOR', 'Ödeme Bekliyor'), ('KISMI', 'Kısmi Ödendi'), ('ODENDI', 'Ödendi')], default='BEKLIYOR', max_length=20, verbose_name='Ödeme Durumu')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ödenen Tutar')),
                ('delivery_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teslim Km')),
                ('return_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='İade Km')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Onay Bildirimi Gönderildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rentals', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.customer', verbose_name='Müşteri')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='vehicles.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Kiralama',
                'verbose_name_plural': 'Kiralamalar',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=50, unique=True, verbose_name='Sözleşme No')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Sözleşme Dosyası')),
                ('terms', models.TextField(blank=True, verbose_name='Sözleşme Şartları')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='İmza Tarihi')),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Sözleşme',
                'verbose_name_plural': 'Sözleşmeler',
            },
        ),
    ]
