# Generated by Django 5.0.6 on 2026-09-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_no',
            field=models.CharField(default='', editable=False, max_length=20, unique=True, verbose_name='Kiralama No'),
        ),
    ]
