# Generated by Django 5.0.6 on 2026-09-15 13:47

import apps.rentals.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_rental_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='driver_license_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tc_or_tax_no',
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name='Fatura Adresi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Firma Unvanı'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Yetkili Kişi E-posta'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Yetkili Kişi Ad Soyad'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Yetkili Kişi Telefon'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('SAHIS', 'Şahıs'), ('TUZEL', 'Tüzel')], default='SAHIS', max_length=10, verbose_name='Müşteri Tipi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_no',
            field=models.CharField(blank=True, max_length=10, validators=[apps.rentals.validators.validate_tax_no], verbose_name='Vergi No'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_office',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tc_no',
            field=models.CharField(blank=True, max_length=11, validators=[apps.rentals.validators.validate_tc_no], verbose_name='T.C. Kimlik No'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('tc_no', models.CharField(blank=True, max_length=11, validators=[apps.rentals.validators.validate_tc_no], verbose_name='T.C. Kimlik No')),
                ('passport_no', models.CharField(blank=True, max_length=30, verbose_name='Pasaport No')),
                ('address', models.TextField(blank=True, verbose_name='İkamet Adresi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('license_no', models.CharField(blank=True, max_length=30, verbose_name='Ehliyet No')),
                ('license_class', models.CharField(blank=True, max_length=10, verbose_name='Ehliyet Sınıfı')),
                ('license_issue_place', models.CharField(blank=True, max_length=100, verbose_name='Ehliyetin Verildiği Yer')),
                ('license_issue_date', models.DateField(blank=True, null=True, verbose_name='Ehliyetin Veriliş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='rentals.customer', verbose_name='İlgili Müşteri')),
            ],
            options={
                'verbose_name': 'Sürücü',
                'verbose_name_plural': 'Sürücüler',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='rental',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='rentals.driver', verbose_name='Aracı Kullanacak Kişi'),
        ),
    ]
