# Generated by Django 5.0.6 on 2026-09-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_remove_customer_driver_license_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Tutar'),
        ),
    ]
