# Generated by Django 5.0.6 on 2026-09-16 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_rental_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(default='', editable=False, max_length=7, verbose_name='Müşteri No'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Örn. Merkez, Şube - Kadıköy', max_length=100, verbose_name='Adres Etiketi')),
                ('address_type', models.CharField(choices=[('FATURA', 'Fatura'), ('TESLIMAT', 'Teslimat'), ('HER_IKISI', 'Her İkisi de')], default='FATURA', max_length=10, verbose_name='Adres Tipi')),
                ('address', models.TextField(verbose_name='Adres')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='rentals.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
                'ordering': ['-is_default', 'label'],
            },
        ),
    ]
