# Generated by Django 5.0.6 on 2026-09-16 14:32
from django.db import migrations


def backfill(apps, schema_editor):
    Customer = apps.get_model("rentals", "Customer")
    Address = apps.get_model("rentals", "Address")

    # 1) Müşteri numarasını oluşturulma tarihine göre sırayla ata (0000001'den başlar).
    customers = list(Customer.objects.order_by("created_at", "id"))
    for index, customer in enumerate(customers, start=1):
        customer.customer_number = f"{index:07d}"
    Customer.objects.bulk_update(customers, ["customer_number"])

    # 2) Eski tekil "Fatura Adresi" (billing_address) alanını yeni Address tablosuna taşı.
    moved_count = 0
    for customer in customers:
        billing_address = (getattr(customer, "billing_address", "") or "").strip()
        if billing_address:
            Address.objects.create(
                customer_id=customer.id,
                label="Fatura Adresi",
                address_type="FATURA",
                address=billing_address,
                is_default=True,
            )
            moved_count += 1

    print(f"\n  [backfill_customer_number_and_addresses] {len(customers)} müşteriye numara atandı, {moved_count} fatura adresi taşındı.")


def reverse_backfill(apps, schema_editor):
    Customer = apps.get_model("rentals", "Customer")
    Address = apps.get_model("rentals", "Address")
    Address.objects.filter(label="Fatura Adresi").delete()
    Customer.objects.update(customer_number="")


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_customer_billing_address_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse_backfill),
    ]
