# Generated by Django 5.0.6 on 2026-09-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_backfill_customer_number_and_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='billing_address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(default='', editable=False, max_length=7, unique=True, verbose_name='Müşteri No'),
        ),
    ]
