# Generated by Django 5.0.6 on 2026-09-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_move_legacy_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
