# Generated by Django 5.0.6 on 2026-09-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0009_remove_customer_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="actual_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Gerçek Teslim Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="provision_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Kiralama oluşturulurken/tipi değiştiğinde ayarlardaki güncel değerden otomatik kopyalanır, sonradan ayar değişse bile sabit kalır.",
                max_digits=10,
                verbose_name="Provizyon Tutarı",
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="provision_deduction_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Provizyon Kesinti Tutarı",
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="provision_refund_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Provizyon İade Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="provision_status",
            field=models.CharField(
                choices=[
                    ("ALINDI", "Alındı"),
                    ("IADE_EDILDI", "İade Edildi"),
                    ("KISMEN_KESILDI", "Kısmen Kesildi"),
                ],
                default="ALINDI",
                max_length=20,
                verbose_name="Provizyon Durumu",
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="provision_type",
            field=models.CharField(
                choices=[("YOK", "Yok"), ("EKONOMIK", "Ekonomik"), ("LUKS", "Lüks")],
                default="YOK",
                max_length=10,
                verbose_name="Provizyon Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="end_date",
            field=models.DateField(verbose_name="Planlanan Bitiş Tarihi"),
        ),
    ]
