# Generated by Django 5.0.6 on 2026-09-15 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField(auto_now_add=True, verbose_name='Bildirim Tarihi')),
                ('description', models.TextField(verbose_name='Hasar Açıklaması')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='damages/%Y/%m/', verbose_name='Fotoğraf')),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Onarım Maliyeti')),
                ('status', models.CharField(choices=[('ACIK', 'Açık'), ('SERVISTE', 'Serviste'), ('KAPALI', 'Kapatıldı')], default='ACIK', max_length=20, verbose_name='Durum')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='Kapatılma Tarihi')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damages', to='rentals.rental', verbose_name='İlgili Kiralama')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_damages', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='vehicles.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Hasar Kaydı',
                'verbose_name_plural': 'Hasar Kayıtları',
                'ordering': ['-reported_date'],
            },
        ),
    ]
