# Generated by Django 5.0.6 on 2026-09-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Plaka')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Model Yılı')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Renk')),
                ('chassis_no', models.CharField(blank=True, max_length=50, verbose_name='Şasi No')),
                ('engine_no', models.CharField(blank=True, max_length=50, verbose_name='Motor No')),
                ('fuel_type', models.CharField(blank=True, max_length=30, verbose_name='Yakıt Tipi')),
                ('transmission', models.CharField(blank=True, max_length=30, verbose_name='Vites Tipi')),
                ('km', models.PositiveIntegerField(default=0, verbose_name='Kilometre')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Günlük Fiyat')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aylık Fiyat')),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yıllık Fiyat')),
                ('status', models.CharField(choices=[('MUSAIT', 'Müsait'), ('KIRADA', 'Kirada'), ('BAKIMDA', 'Bakımda'), ('HASARLI', 'Hasarlı - Serviste'), ('PASIF', 'Pasif / Filodan Çıkarıldı')], default='MUSAIT', max_length=20, verbose_name='Durum')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Filoya Katılım Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
                'ordering': ['plate'],
            },
        ),
    ]
