# Generated by Django 5.0.6 on 2026-09-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fleet_contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Filo Sözleşme Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sonraki Bakım Tarihi'),
        ),
    ]
