# Generated by Django 5.0.6 on 2026-09-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_fleet_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='estimated_resolution_date',
            field=models.DateField(blank=True, help_text='Hasarlı araçlar için opsiyonel — süreç genelde belirsizdir.', null=True, verbose_name='Tahmini Çözüm Tarihi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='estimated_service_end_date',
            field=models.DateField(blank=True, help_text='Araç Serviste iken bu bakımın ne zaman biteceğini belirtir.', null=True, verbose_name='Tahmini Servis Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('MUSAIT', 'Müsait'), ('KIRADA', 'Kirada'), ('SERVISTE', 'Serviste'), ('HASARLI', 'Hasarlı'), ('PASIF', 'Pasif / Filodan Çıkarıldı')], default='MUSAIT', max_length=20, verbose_name='Durum'),
        ),
    ]
