# Generated by Django 5.0.6 on 2026-09-16 09:15
from django.db import migrations


def move_bakimda_to_serviste(apps, schema_editor):
    """
    Vehicle.Status "BAKIMDA" değeri "SERVISTE" ile değiştirildi (HASARLI zaten
    ayrı bir değerdi, ona dokunulmuyor). Eski "BAKIMDA" kayıtlarını SERVISTE'ye
    taşıyıp taşınan/etkilenmeyen kayıt sayılarını migrate çıktısında raporlar.
    """
    Vehicle = apps.get_model("vehicles", "Vehicle")
    moved_count = Vehicle.objects.filter(status="BAKIMDA").update(status="SERVISTE")
    hasarli_count = Vehicle.objects.filter(status="HASARLI").count()
    print(
        f"\n  [move_bakimda_to_serviste] {moved_count} araç 'Bakımda' -> 'Serviste' olarak taşındı. "
        f"{hasarli_count} araç zaten 'Hasarlı' durumundaydı, dokunulmadı."
    )


def reverse_move(apps, schema_editor):
    Vehicle = apps.get_model("vehicles", "Vehicle")
    Vehicle.objects.filter(status="SERVISTE").update(status="BAKIMDA")


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_estimated_resolution_date_and_more'),
    ]

    operations = [
        migrations.RunPython(move_bakimda_to_serviste, reverse_move),
    ]
