# Generated by Django 5.0.6 on 2026-09-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_move_bakimda_to_serviste"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="acquisition_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Satın Alma Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="purchase_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Satın Alma Maliyeti",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BEYAZ", "Beyaz"),
                    ("SIYAH", "Siyah"),
                    ("GRI", "Gri"),
                    ("GUMUS", "Gümüş"),
                    ("KIRMIZI", "Kırmızı"),
                    ("MAVI", "Mavi"),
                    ("LACIVERT", "Lacivert"),
                    ("YESIL", "Yeşil"),
                    ("SARI", "Sarı"),
                    ("TURUNCU", "Turuncu"),
                    ("KAHVERENGI", "Kahverengi"),
                    ("BORDO", "Bordo"),
                    ("BEJ", "Bej"),
                    ("TURKUAZ", "Turkuaz"),
                    ("MOR", "Mor"),
                    ("ALTIN", "Altın"),
                    ("DIGER", "Diğer"),
                ],
                max_length=30,
                verbose_name="Renk",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="daily_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="DEPRECATED: artık her kiralamada elle girilir, araç kaydında kullanılmıyor.",
                max_digits=10,
                null=True,
                verbose_name="Günlük Fiyat",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="next_maintenance_date",
            field=models.DateField(
                blank=True,
                help_text="DEPRECATED: bakım takibi ileride ayrı bir Bakım modülü altında ele alınacak, formdan kaldırıldı.",
                null=True,
                verbose_name="Sonraki Bakım Tarihi",
            ),
        ),
    ]
