# Generated by Django 5.0.6 on 2026-09-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "economy_provision_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000,
                        max_digits=10,
                        verbose_name="Ekonomik Sınıf Provizyon Tutarı",
                    ),
                ),
                (
                    "luxury_provision_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        max_digits=10,
                        verbose_name="Lüks Sınıf Provizyon Tutarı",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sistem Ayarları",
                "verbose_name_plural": "Sistem Ayarları",
            },
        ),
    ]
