# Generated by Django 5.0.6 on 2026-09-15 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_inspection_date', models.DateField(verbose_name='Son Muayene Tarihi')),
                ('next_inspection_date', models.DateField(verbose_name='Bir Sonraki Muayene Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='vehicles.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Muayene Kaydı',
                'verbose_name_plural': 'Muayene Kayıtları',
                'ordering': ['next_inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PERIYODIK', 'Periyodik Bakım'), ('ARIZA', 'Arıza Onarımı'), ('LASTIK', 'Lastik Değişimi'), ('DIGER', 'Diğer')], default='PERIYODIK', max_length=20, verbose_name='Tür')),
                ('service_date', models.DateField(verbose_name='Servis Tarihi')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Bir Sonraki Bakım Tarihi')),
                ('next_due_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bir Sonraki Bakım Km')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maliyet')),
                ('service_provider', models.CharField(blank=True, max_length=100, verbose_name='Servis/Yetkili Bayi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicles.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Bakım Kaydı',
                'verbose_name_plural': 'Bakım Kayıtları',
                'ordering': ['-service_date'],
            },
        ),
    ]
