# Generated by Django 5.0.6 on 2026-09-15 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HGSExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Geçiş Noktası')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_hgs', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hgs_expenses', to='rentals.rental', verbose_name='İlgili Kiralama')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hgs_expenses', to='vehicles.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'HGS Harcaması',
                'verbose_name_plural': 'HGS Harcamaları',
                'ordering': ['-date'],
            },
        ),
    ]
